# a mybinder.org-ready environment for demoing amazon-codeguru-extension
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   conda env update --file binder/environment.yml
#   conda activate amazon-codeguru-extension-demo
#
name: amazon-codeguru-extension-demo

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - python >=3.8,<3.9.0a0
  - jupyterlab >=3,<4.0.0a0
  - python-lsp-server <= 1.7.1
  # labextension build dependencies
  - nodejs >=18,<19
  - pip
  - wheel
  # build dependencies
  - build
  - twine
  - hatch
  # test dependencies
  - pytest
  - coverage
