name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: amazon-codeguru-extension-demo
        environment-file: binder/environment.yml
    - run: pip install -e "."
    - run: pytest
